import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#e0e2ec",
        "secondary-fixed-dim": "#aec7f9",
        "surface-dim": "#d8d9e3",
        tertiary: "#9b3f00",
        "on-tertiary-fixed": "#341000",
        outline: "#717785",
        "secondary-fixed": "#d7e2ff",
        "outline-variant": "#c1c6d6",
        primary: "#0071E3",
        error: "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#181c23",
        "error-container": "#ffdad6",
        "on-primary-fixed": "#001b3f",
        "on-tertiary-container": "#fffaf9",
        "surface-bright": "#f9f9ff",
        "surface-tint": "#005cbb",
        "on-secondary-fixed": "#001b3f",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#c25100",
        "primary-fixed": "#d7e2ff",
        "on-tertiary-fixed-variant": "#7a3000",
        "on-secondary": "#ffffff",
        background: "#ffffff",
        "tertiary-fixed-dim": "#ffb693",
        "surface-container-low": "#f2f3fd",
        "on-secondary-container": "#3e5682",
        "tertiary-fixed": "#ffdbcb",
        "secondary-container": "#b4ccff",
        "inverse-surface": "#2d3038",
        "inverse-on-surface": "#eff0fa",
        "inverse-primary": "#abc7ff",
        "on-background": "#1D1D1F",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#abc7ff",
        "surface-container-high": "#e6e8f2",
        "on-error": "#ffffff",
        "surface-container": "#ecedf7",
        "on-secondary-fixed-variant": "#2e4772",
        "surface-variant": "#EDEDF2",
        "primary-container": "#0071e3",
        "on-primary-fixed-variant": "#00458f",
        "on-primary-container": "#fcfbff",
        "on-error-container": "#93000a",
        "on-surface-variant": "#6E6E73",
        secondary: "#465e8b",
        surface: "#ffffff",
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
      spacing: {
        "max-width": "1262px",
        "margin-tablet": "40px",
        "margin-desktop": "56px",
        "stack-md": "40px",
        "stack-lg": "80px",
        "margin-mobile": "20px",
        gutter: "24px",
      },
      maxWidth: {
        "max-width": "1262px",
      },
      fontFamily: {
        "hero-mobile": ["Inter", "sans-serif"],
        "large-heading": ["Inter", "sans-serif"],
        eyebrow: ["Inter", "sans-serif"],
        hero: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        "primary-heading": ["Inter", "sans-serif"],
      },
      fontSize: {
        "hero-mobile": ["32px", { lineHeight: "1.2", fontWeight: "600" }],
        "large-heading": ["28px", { lineHeight: "1.3", fontWeight: "400" }],
        eyebrow: [
          "12px",
          { lineHeight: "1.1", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        hero: [
          "40px",
          { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" },
        ],
        body: ["17px", { lineHeight: "1.5", fontWeight: "400" }],
        "primary-heading": ["24px", { lineHeight: "1.4", fontWeight: "600" }],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
